title = "Nico Kaiser"
#baseURL = "https://kaiser.gallery/"
languageCode = "de-de"
author = "Nico Kaiser"
copyright = "© Nico Kaiser"
disableKinds = ["taxonomy", "taxonomyTerm"]
defaultContentLanguage = "de"
enableRobotsTXT = true
timeout = "120s"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  description = "Capturing moments, music, people and events"

[imaging]
  resampleFilter = "CatmullRom"
  quality = 75
