title = "Nico Kaiser"
#baseURL = "https://kaiser.gallery/"
languageCode = "de-de"
author = "Nico Kaiser"
copyright = "© Nico Kaiser"
disableKinds = ["taxonomy", "taxonomyTerm"]
defaultContentLanguage = "de"
enableRobotsTXT = true

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[imaging]
  resampleFilter = "CatmullRom"
  quality = 75
