title = "Nico Kaiser"
baseURL = "https://kaiser.gallery/"
languageCode = "de-de"
copyright = "© Nico Kaiser"
disableKinds = ["taxonomy", "term"]
defaultContentLanguage = "de"
enableRobotsTXT = true

[author]
  name = "Nico Kaiser"

[outputs]
  page = ["HTML"]
  home = ["HTML", "RSS"]
  section = ["HTML"]

[sitemap]
  changefreq = "daily"
  priority = 0.5
  filename = "sitemap.xml"

[imaging]
  resampleFilter = "CatmullRom"
  quality = 75
  [imaging.exif]
    disableDate = false
    disableLatLong = true
