title = "Nico Kaiser"
baseURL = "https://kaiser.gallery/"
languageCode = "de-de"
author = "Nico Kaiser"
copyright = "© Nico Kaiser"
disableKinds = ["taxonomy", "term"]
defaultContentLanguage = "de"
enableRobotsTXT = true

[sitemap]
  changefreq = "daily"
  priority = 0.5
  filename = "sitemap.xml"

[imaging]
  resampleFilter = "CatmullRom"
  quality = 75
  [imaging.exif]
    disableDate = false
    disableLatLong = true
